export const NODE_MODULE_GENERATOR_TEST_ANSWERS = {
  name: "test-package",
  description: "This is a test package generated by Yeoman.",
  authorName: "Jon Smith",
  authorEmail: "jon@example.com",
  githubUrl: "https://github.com/chiubaka/test-package",
  keywords: "test chiubaka-technologies",
};
