env:
  browser: true
  es2021: true
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended
  - plugin:security/recommended
overrides:
  - files: "**/*.@(test|spec).@(t|j)s?(x)"
    plugins:
      - jest
    extends:
      - plugin:jest/recommended
      - plugin:jest/style
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  project: tsconfig.json
  sourceType: module
plugins:
  - "@typescript-eslint"
  - prettier
  - simple-import-sort
rules:
  jest/expect-expect:
    - error
    - assertFunctionNames:
        - "*.assert*"
  no-console:
    - error
    - allow:
      - warn
      - error
  simple-import-sort/exports: error
  simple-import-sort/imports:
    - error
    # See https://github.com/lydell/eslint-plugin-simple-import-sort/#custom-grouping
    - groups:
      -
        # Side effect imports (the plugin inserts '\\u0000' for us to match).
        - ^\u0000
      -
        # Packages. (Things that start with a letter (or digit or underscore), or `@` followed by a letter.)
        - ^@?\w
      -
        # Relative imports.
        - ^\.
      -
        # Catch everything not covered by other rules
        - ^
