env:
  browser: true
  es2021: true
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended
  - plugin:security/recommended
  - plugin:promise/recommended
overrides:
  - files: "**/*.@(test|spec).@(t|j)s?(x)"
    plugins:
      - jest
    extends:
      - plugin:jest/recommended
      - plugin:jest/style
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  project: tsconfig.json
  sourceType: module
plugins:
  - "@typescript-eslint"
  - prettier
  - promise
  - simple-import-sort
rules:
  "@typescript-eslint/interface-name-prefix": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-namespace":
    - error
    - allowDeclarations: true
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  "@typescript-eslint/no-this-alias":
    - error
    - allowedNames:
        - self
  "@typescript-eslint/unbound-method":
    - error
    - ignoreStatic: true
  jest/expect-expect:
    - error
    - assertFunctionNames:
        - "*.assert*"
  no-console:
    - error
    - allow:
      - warn
      - error
  promise/catch-or-return:
    - error
    - terminationMethod:
        - catch
        - finally
  simple-import-sort/exports: error
  simple-import-sort/imports:
    - error
    # See https://github.com/lydell/eslint-plugin-simple-import-sort/#custom-grouping
    - groups:
      -
        # Side effect imports (the plugin inserts '\\u0000' for us to match).
        - ^\u0000
      -
        # Packages. (Things that start with a letter (or digit or underscore), or `@` followed by a letter.)
        - ^@?\w
      -
        # Relative imports.
        - ^\.
      -
        # Catch everything not covered by other rules
        - ^
