import path from "node:path";

import PackageJson from "../package.symlink.json";
import { BaseGenerator } from "../shared";
import GitHooksGenerator from "./git-hooks";

export class GitGenerator extends BaseGenerator {
  public async writing() {
    await this.exec("git init");
    if (
      process.env.NODE_ENV === "test" &&
      this.options.configGitUser === true
    ) {
      await this.exec("git config user.email testing@jest.io");
      await this.exec("git config user.name Jest");
    }
  }

  public async end() {
    const commitMessage = `Add/update files generated by ${PackageJson.name} v${PackageJson.version}`;
    await this.exec("git add .");
    await this.exec(`git commit -m "${commitMessage}" --no-verify`);
  }

  protected configureSubGenerators = () => {
    return [
      {
        Generator: GitHooksGenerator,
        path: path.join(__dirname, "./git-hooks"),
      },
    ];
  };
}
