%YAML 1.1
---
version: 2.1

constants:
  # Semantic versioning RegEx from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
  semver-regex: &semver-regex /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

orbs:
  node: circleci/node@5.0.2

executors:
  node-executor:
    docker:
      - image: cimg/node:16.10

commands:
  setup:
    steps:
      - checkout
      - run:
          name: Use Yarn Berry
          command: yarn set version berry
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false

filters:
  semver-tags: &semver-tags
    tags:
      only: *semver-regex
  ignore-branches: &ignore-branches
    branches:
      ignore: /.*/

jobs:
  build:
    executor: node-executor
    steps:
      - setup
      - run:
          name: Build code
          command: yarn run build
  lint:
    executor: node-executor
    steps:
      - setup
      - run:
          name: Lint code
          command: yarn run lint
  test:
    executor: node-executor
    steps:
      - setup
      - run:
          name: Run tests
          command: yarn run test:ci
      - run:
          name: Move JUnit report to reports directory
          command: mkdir -p ./reports/junit && mv junit.xml ./reports/junit/
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
  publish:
    executor: node-executor
    steps:
      - setup
      - run:
          name: Publish to NPM
          command: yarn run deploy

workflows:
  lint-build-test-publish:
    jobs:
      - lint:
          filters:
            <<: *semver-tags
      - build:
          filters:
            <<: *semver-tags
      - test:
          filters:
            <<: *semver-tags
      - publish:
          requires:
            - lint
            - build
            - test
          filters:
            <<: *ignore-branches
            <<: *semver-tags
